# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\python code\qt\PYQT\Resource\Ui\MainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(651, 393)
        self.layoutWidget = QtWidgets.QWidget(MainWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 561, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.inAlgFilePath = QtWidgets.QLineEdit(self.layoutWidget)
        self.inAlgFilePath.setObjectName("inAlgFilePath")
        self.horizontalLayout_2.addWidget(self.inAlgFilePath)
        self.seleteAlgButton = QtWidgets.QPushButton(self.layoutWidget)
        self.seleteAlgButton.setObjectName("seleteAlgButton")
        self.horizontalLayout_2.addWidget(self.seleteAlgButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.outZipFilePath = QtWidgets.QLineEdit(self.layoutWidget)
        self.outZipFilePath.setObjectName("outZipFilePath")
        self.horizontalLayout_3.addWidget(self.outZipFilePath)
        self.seleteOutZipButton = QtWidgets.QPushButton(self.layoutWidget)
        self.seleteOutZipButton.setObjectName("seleteOutZipButton")
        self.horizontalLayout_3.addWidget(self.seleteOutZipButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "Form"))
        self.label_3.setText(_translate("MainWidget", "生成行为自定义："))
        self.label.setText(_translate("MainWidget", "算法行为配置文件："))
        self.seleteAlgButton.setText(_translate("MainWidget", "选择"))
        self.label_2.setText(_translate("MainWidget", "导出压缩包地址："))
        self.seleteOutZipButton.setText(_translate("MainWidget", "选择"))
